apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: kirillkhlebov/todo-app
        env:
        - name: PGHOST
          value: "dbs"
        - name: PGUSER
          value: "admin"
        - name: PGPASSWORD
          value: "password"
        - name: PGDATABASE
          value: "todo"
        ports:
        - containerPort: 3000
